### PR TITLE
Gh pages update

### LINKED ISSUE #79: Update gh-pages
Could you update gh-pages so that https://estools.github.io/esquery/ is against the current version, or, better yet, use Github's ability under Settings to have the github.io URL point to `master` so it is always up to date?

Thanks!

### PR DESCRIPTION
**Pull request by brettz9**
~Builds on #81, #82, #83, #84, and #85~. Fixes #79.

Works, but awaiting a possible release for previous PRs, so can point to updated dependency in the demo.

- Refactoring: Move index.html demo CSS and JS into own files
- Update: Point redirect to `estools`
- Lint: HTML - Build: Rollup esquery (now as dep.) and of espree (changed from esprima)
- Styling: Add minimum height to textarea
- Add `.editorconfig` and .eslintrc.js (tweaking to gh-pages needs)
- Merge npmrc, travis.yml, and README

### CODE REVIEW

**Comment by brettz9** [comment]
Whenever you may be ready for a new npm release, this PR would just need to point to it in order to be ready from my perspective (there could be more linting, but there's always the risk the newer features aren't supported in some older browsers).

**Comment by michaelficarra** [comment]
@brettz9 Do you have any opinion on whether a major bump is warranted? On one hand, we've dropped support for some engines, but on the other hand, they were out of maintenance anyway.

**Comment by brettz9** [comment]
I think the most common practice from what I have seen is to make the major bump, even when the only change is due to EOL.

If someone is still depending on an older Node version, they won't be disturbed by the changes. (There may sometimes inevitably be "breaking" changes when any fix is applied, but I think he semver "contract" is basically that nothing should break if the user was using the previous version as advertised)

For projects which check for major updates (as I like to do), there is only the minor downside in having a little extra work of reviewing the reasons for the bump, but when the change log makes it clear at a glance that that is the only breaking change, I think this is part and parcel, with the downside negligible.

The only real downside I see is that it doesn't get automatically applied for existing projects, but hopefully the larger projects using esquery like eslint will get informed of the bump (e.g., if its maintainers use the likes of `npm-check-updates`) and then add it.

Just my two cents...

**Comment by brettz9** [comment]
While ideally I think your work would be integrated into https://astexplorer.net/ as a befitting demo, I think it would be nice for the gh-pages branch to have a simple radio button to toggle the parser between babel-eslint, typescript-eslint, and esprima (and maybe espree since it comes with the devDep. eslint anyways) if that's ok with you.

**Comment by michaelficarra** [comment]
@brettz9 Thanks for getting this started. I merged with a few tweaks. You can check it out on [the `gh-pages` branch](https://github.com/estools/esquery/tree/gh-pages). I've also released `v1.2.0` and built `gh-pages` against that.

**Pull request merged**
