### PR TITLE
Fix global leak due to missing var declaration of l

### PR DESCRIPTION
**Pull request by papandreou**

### CODE REVIEW

**Comment by brettz9** [comment]
This looks like a no-brainer... 

Is the library being maintained? If not, do you need any help therewith?

**Comment by michaelficarra** [comment]
@brettz9 If you're offering, it would be great for someone to send in a PR that sets up eslint in this repo and enforces a rule that would've caught this issue.

**Comment by papandreou** [comment]
I'd be happy to help with that, but it won't be possible to get a recent version of eslint to run in any of [the node versions that this project is being tested with](https://github.com/estools/esquery/blob/1bf928025a35b6406e9fe4dcd5e785131838204a/.travis.yml#L4-L7). The eslint 7 betas are only support node.js 10+. Would it be OK to align with that here, or do we need a setup where linting is a separate CI job running with a newer node?

**Comment by michaelficarra** [comment]
I'd prefer we just add support for newer node and only run eslint in jobs that have a recent enough node. We only need it to run (and potentially fail) on a single job. How do you feel about that?

**Pull request merged**
